#
# ~/.bashrc
#
eval "$(starship init bash)"
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

alias update='sudo pacman -Syu && sudo pacman -Sy && yay && flatpak update'
alias cleanshot='rm -rf ~/screenshot/output/* && rm -rf ~/screenshot/region/* && rm -rf ~/screenshot/window/*'
alias nvidia='sudo mkinitcpio -P'
alias resetwaybar='killall waybar && hyprctl dispatch exec waybar'
alias install='sudo pacman -S'
alias remove='sudo pacman -Rs'
alias resetwallpaper='killall hyprpaper && hyprctl dispatch exec hyprpaper'
alias z="cd"


fastfetch
