# ~/.tmux.conf

# ================================
# ESSENTIAL
# ================================

# Faster ESC in vim
set -sg escape-time 0

# Bigger scrollback
set -g history-limit 50000

# Start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Mouse support
set -g mouse on

# colors
set -g pane-active-border-style fg='#6272a4'
set -g pane-border-style fg='#ff79c6'

set -g default-terminal "screen-256color"

set -g status-bg blue
set -g status-fg white

# ================================
# PREFIX
# ================================

# Reload config
bind r source-file ~/.tmux.conf \; display "reloaded"

# ================================
# PANES / WINDOWS
# ================================

# Split panes in current directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Vim navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ================================
# COPY MODE
# ================================

setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

