# ~/.zshrc - minimal and stable

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=5000
SAVEHIST=5000

setopt appendhistory
setopt sharehistory
setopt hist_ignore_dups
setopt hist_ignore_space
setopt autocd
#setopt correct
setopt interactivecomments

# Completion
autoload -Uz compinit
compinit

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# Prompt
autoload -Uz colors && colors

PROMPT='%F{cyan}%n%f %F{blue}%~%f %# '
RPROMPT=''

# Aliases
alias ls='eza --icons --group-directories-first'
alias ll='eza -lah --icons --group-directories-first'
alias la='eza -A --icons --group-directories-first'
alias tree='eza --tree --icons'
alias cat='bat'
alias grep='grep --color=auto'
alias ..='cd ..'
alias ...='cd ../..'

eval "$(zoxide init zsh)"

alias update='sudo pacman -Syu'

alias cleanshot='rm -rf ~/screenshot/output/* && rm -rf ~/screenshot/region/* && rm -rf ~/screenshot/window/*'
alias nvidia='sudo mkinitcpio -P'
alias resetwaybar='killall waybar && hyprctl dispatch exec waybar'


# Useful functions
mkcd() {
  mkdir -p "$1" && cd "$1"
}

extract() {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2) tar xjf "$1" ;;
      *.tar.gz)  tar xzf "$1" ;;
      *.bz2)     bunzip2 "$1" ;;
      *.rar)     unrar x "$1" ;;
      *.gz)      gunzip "$1" ;;
      *.tar)     tar xf "$1" ;;
      *.tbz2)    tar xjf "$1" ;;
      *.tgz)     tar xzf "$1" ;;
      *.zip)     unzip "$1" ;;
      *.7z)      7z x "$1" ;;
      *)         echo "Cannot extract: $1" ;;
    esac
  else
    echo "File not found: $1"
  fi
}

# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Custom Soulseek Batch Downloader Shortcut
alias slsk="~/.config/rmpc/script/slsk-flow"

# Auto-start
if command -v fastfetch >/dev/null 2>&1; then
  fastfetch
fi
