### KEYBINDINGS ###

$Super = SUPER
$Alt = ALT

# Return = Enter

# Launchers
bind = $Alt, S, exec, $terminal --class rmpc -e rmpc
bind = $Alt, B, exec, $browser
bind = $Alt, D, exec, vesktop
bind = $Super, Space, exec, $menu
bind = $Super SHIFT, Space, exec, $wall
bind = $Super, Return, exec, $terminal
bind = $Super, E, exec, $fileManager

# Clipboard menu
bind = $Super, V, exec, cliphist list | rofi -dmenu -p "Clipboard" | cliphist decode | wl-copy

# Power / lock
bind = $Super, P, exec, wlogout --buttons-per-row 2
bind = $Super, O, exec, hyprlock

# Music controls
bind = $Alt, Space, exec, $pause
bind = $Alt, Right, exec, $next_song
bind = $Alt, Left, exec, $previous_song
bind = $Alt, Down, exec, $less_volume
bind = $Alt, Up, exec, $more_volume

# Special workspace
bind = $Super, T, togglespecialworkspace, magic
bind = $Super SHIFT, G, movetoworkspace, special:magic
bind = $Super, G, movetoworkspace, 2

# Screenshots
bind = $Super, X, exec, $printregion
bind = $Super, Z, exec, $print
bind = $Super, C, exec, $printwindow

# Notifications
bind = $Super, N, exec, dunstctl history-pop
bind = $Super SHIFT, N, exec, dunstctl close-all
bind = $Super CTRL, N, exec, dunstctl set-paused toggle

# Windows
bind = $Super, Q, killactive
bind = $Super, F, togglefloating
bind = $Super, I, fullscreen

bind = $Super SHIFT, h, swapwindow, l
bind = $Super SHIFT, l, swapwindow, r
bind = $Super SHIFT, k, swapwindow, u
bind = $Super SHIFT, j, swapwindow, d

bind = $Super, h, movefocus, l
bind = $Super, l, movefocus, r
bind = $Super, k, movefocus, u
bind = $Super, j, movefocus, d

# Workspaces
bind = $Super, 1, workspace, 1
bind = $Super, 2, workspace, 2
bind = $Super, 3, workspace, 3
bind = $Super, 4, workspace, 4
bind = $Super, 5, workspace, 5
bind = $Super, 6, workspace, 6
bind = $Super, 7, workspace, 7
bind = $Super, 8, workspace, 8
bind = $Super, 9, workspace, 9
bind = $Super, 0, workspace, 10

bind = $Super SHIFT, 1, movetoworkspace, 1
bind = $Super SHIFT, 2, movetoworkspace, 2
bind = $Super SHIFT, 3, movetoworkspace, 3
bind = $Super SHIFT, 4, movetoworkspace, 4
bind = $Super SHIFT, 5, movetoworkspace, 5
bind = $Super SHIFT, 6, movetoworkspace, 6
bind = $Super SHIFT, 7, movetoworkspace, 7
bind = $Super SHIFT, 8, movetoworkspace, 8
bind = $Super SHIFT, 9, movetoworkspace, 9
bind = $Super SHIFT, 0, movetoworkspace, 10

# Mouse window controls
bindm = $Super, mouse:272, movewindow
bindm = $Super, mouse:273, resizewindow

# Laptop multimedia keys
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Player controls
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
