###################
### KEYBINDINGS ###
###################

$Super = SUPER # Sets "Windows" key
$Alt = ALT # Sets the "ALT" key

# LAUNCHE
bind = $Alt, S, exec, spotify
bind = $Alt, B, exec, $browser
bind = $Alt, D, exec, vesktop
bind = $Super, Space, exec, $menu
bind = $Super $Alt, Space, exec, $wall
bind = $Super, E, exec, $terminal
bind = $Super SHIFT, E, exec, $fileManager 

#spotify
bind = $Alt, left, exec, $pause
bind = $Alt, down, exec, $less_volume 
bind = $Alt, up, exec, $more_volume
bind = $Alt, right, exec, $next_soung

# Special workspace
bind = $Super, T, togglespecialworkspace, magic
bind = $Super SHIFT, G, movetoworkspace, special:magic
bind = $Super, G, movetoworkspace, 2

# PRINT
bind = $Super, X, exec, $printregion
bind = $Super, Z, exec, $print
bind = $Super, C, exec, $printwindow

# WINDOWS
bind = $Super, Q, killactive
bind = $Super, F, togglefloating
bind = $Super, I, fullscreen
bind = $Super SHIFT, h, swapwindow, l
bind = $Super SHIFT, l, swapwindow, r
bind = $Super SHIFT, k, swapwindow, u
bind = $Super SHIFT, j, swapwindow, d
bind = $Super, h, movefocus, l
bind = $Super, l, movefocus, r
bind = $Super, k, movefocus, u
bind = $Super, j, movefocus, d

# WORKSPACES
bind = $Super, 1, workspace, 1
bind = $Super, 2, workspace, 2
bind = $Super, 3, workspace, 3
bind = $Super, 4, workspace, 4
bind = $Super, 5, workspace, 5
bind = $Super, 6, workspace, 6
bind = $Super, 7, workspace, 7
bind = $Super, 8, workspace, 8
bind = $Super, 9, workspace, 9
bind = $Super, 0, workspace, 10
bind = $Super $Alt, 1, movetoworkspace, 1
bind = $Super $Alt, 2, movetoworkspace, 2
bind = $Super $Alt, 3, movetoworkspace, 3
bind = $Super $Alt, 4, movetoworkspace, 4
bind = $Super $Alt, 5, movetoworkspace, 5
bind = $Super $Alt, 6, movetoworkspace, 6
bind = $Super $Alt, 7, movetoworkspace, 7
bind = $Super $Alt, 8, movetoworkspace, 8
bind = $Super $Alt, 9, movetoworkspace, 9
bind = $Super $Alt, 0, movetoworkspace, 10


# MOVE WINDOWS WITH THE MOUSE
bindm = $Super, mouse:272, movewindow
bindm = $Super, mouse:273, resizewindow


# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-


# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
