###   ROLES     ###

#lanche
$terminal = kitty
$fileManager = nemo
$browser = librewolf
$menu = rofi -show drun
$wall = ~/.config/hypr/script/rofi-wallpaper.sh

#print
$print = hyprshot -m output -o ~/screenshot/output/
$printwindow = hyprshot -m window -o ~/screenshot/window/
$printregion = hyprshot -m region -o ~/screenshot/region/

#spotify
$pause = playerctl --player=spotify play-pause
$next_soung = playerctl --player=spotify next
$less_volume = playerctl --player=spotify volume 0.05-
$more_volume = playerctl --player=spotify volume 0.05+

###   AUTO START     ###

exec-once = awww-daemon
exec-once = waybar
exec-once = dunst
exec-once = librewolf
exec-once = spotify
exec-once = vesktop

###   SOURCES     ###

source = ./binds.conf
source = ./lookandfeel.conf
