### MONITORS ###

# Main example monitor.
# Change HDMI-A-1 to your monitor name from:
# hyprctl monitors

monitor = HDMI-A-1, 1920x1080@74.97, 0x0, 1

# Universal fallback.
# This makes the config work on other PCs/monitors.

monitor = , preferred, auto, 1
