###################
###  MONITORS   ###
###################

monitor= HDMI-A-1, 1920x1080@74.97, 0x0, 1
#monitor=,preferred,auto,1

# ----

#workspaces 1

#workspaces 2
windowrule = workspace special:magic silent, match:class ^(spotify)$
windowrule = workspace special:magic silent, match:class ^(vesktop)$

#workspaces 3

#workspaces 4

#workspace 5

###################
###    FLOAT    ###
###################

windowrule = match:class blueman-manager, float on
windowrule = match:title Picture-in-Picture, float on
windowrule = match:class org.pulseaudio.pavucontrol, float on

###################
###   MAX  MIN  ###
###################

windowrule = max_size 535 300, match:title Picture-in-Picture
#windowrule = max_size 930 630, match:initialClass alacrity
