###################
### MY PROGRAMS ###
###################

#lanche
$terminal = kitty
$fileManager = nemo 
$browser = zen-browser
$menu = rofi -show drun
$wall = ~/.config/hypr/scripts/rofi-wallpaper.sh

#print
$print = hyprshot -m output -o ~/screenshot/output/
$printwindow = hyprshot -m window -o ~/screenshot/window/
$printregion = hyprshot -m region -o ~/screenshot/region/

#spotify
$pause = playerctl --player=spotify play-pause
$next_soung = playerctl --player=spotify next
$less_volume = playerctl --player=spotify volume 0.05-
$more_volume = playerctl --player=spotify volume 0.05+
